#!/usr/bin/env bash
# Automates the retrieval of data for multiple Pokémon and store it in separate files

# Loops through a list of Pokémon stored in a JSON file
# Saves each to a separate JSON file named after the Pokémon
# Handles any potential rate-limiting issues by adding a delay between requests
if [ -e data.json ]; then
   urls=$(jq -r '.results[].url' < data.json)

   if [ -d pokemon_data ]; then
      echo "Files are saved to './pokemon_data'"
   else
      mkdir pokemon_data
      echo "Files are saved to the newly created directory - 'pokemon_data'"
   fi

   for url in $urls; do
       api=$(echo "$url")
       name=$(curl -s $api | jq -r .name)
       echo "Fetching data for $name"

       curl -s $api > ./pokemon_data/$name.json

       sleep 2.6s
   done
else
   echo "'data.json' does not exist."
fi

# Handles any error
if [ $? -ne 0 ]; then
   echo "Failed to extract data from 'data.json'" >> errors.txt
fi
