#!/usr/bin/env bash
# Automates the retrieval of data for multiple Pokémon and stores it in separate files
# All API calls are made to:
#     'https://pokeapi.co/api/v2/pokemon/'
# Some of the expected Pokémon names are:
#     "bulbasaur", "ivysaur", "venusaur", "charmander", "charmeleon"

if [ -e data.json ]; then
    urls=$(jq -r '.results[].url' < data.json)

    if [ -d pokemon_data ]; then
        echo "Files are saved to './pokemon_data'"
    else
        mkdir pokemon_data
        echo "Files are saved to the newly created directory - 'pokemon_data'"
    fi

    for api in $urls; do
        retries=0
        max_retries=3
        success=0

        while [ $retries -lt $max_retries ]; do
            response=$(curl -s --fail "$api")
            if [ $? -eq 0 ] && [ -n "$response" ]; then
                name=$(echo "$response" | jq -r '.name')

                if [ -n "$name" ]; then
                    echo "Fetching data for $name"
                    echo "$response" > "./pokemon_data/$name.json"
                    success=1
                    break
                else
                    echo "Error: Missing name field in API response." >> errors.txt
                    break
                fi
            else
                echo "Request failed. Retrying... ($((retries + 1)))"
                retries=$((retries + 1))
                sleep 2
            fi
        done

        if [ $success -ne 1 ]; then
            echo "Failed to fetch data from $api after 3 attempts." >> errors.txt
        fi

        sleep 2.6
    done
else
    echo "'data.json' does not exist."
    echo "Failed to extract data from 'data.json'" >> errors.txt
fi
